---
title: '**`1. Introduction to R`**'
# output: github_document
output: html_document
# keep_md: true
---

## 1.1
 
## 1.2

## 1.3

## 1.4

## 1.5

## 1.6

## 1.7

## 1.8

## 1.9 Using R Markdown

R Markdown provides an easy-to-use authoring framework for your programming work. You can use a single R Markdown (.Rmd) file to both

* record and execute your code
* generate reader-friendly reports that can help your audiences understand your work

I will use R Markdown for most of the empirical analysis I present in this class, and you are required to use R Markdown to show how you solve the empirical questions in your problem sets.

For a quick start-up, the following references are useful:

* [Next generation R Markdown](https://www.youtube.com/watch?v=cWJzjHh_3kk)
* [Using R Markdown for class reports](http://www.stat.cmu.edu/~cshalizi/rmarkdown/)
* [R Markdown cheat sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)
* [R Markdown reference guide](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)

For a more comprehensive introduction, visit <https://rmarkdown.rstudio.com>.

To render your R Markdown to GitHub, you will need to install [Git](https://git-scm.com/) and use RStudio's "version control" tool see [RStudio and GitHub integration](https://www.youtube.com/watch?v=E2d91v1Twcc).
